/**
 * Hand-written Database type matching supabase/migrations/0001_init.sql.
 *
 * This is NOT generated by the Supabase CLI — regenerating requires a real
 * remote project, which doesn't exist yet in this environment (see
 * docs/SUPABASE-SETUP.md). Once Nicolas has a real project, regenerate with:
 *
 *   npx supabase gen types typescript --project-id <project-id> > src/lib/supabase/database.types.ts
 *
 * and reconcile any drift against the tables/columns below (they should
 * match 1:1 if the SQL migration was applied as-is).
 *
 * Shape note: @supabase/supabase-js's generic client requires each schema to
 * satisfy `GenericSchema` (Tables + Views + Functions), and each table to
 * carry a `Relationships` array — see @supabase/postgrest-js's
 * `types/common/common.ts`. This project has no views/functions/foreign-key
 * relationships to describe, so those are intentionally empty.
 */

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          local_migration_version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          local_migration_version?: number;
        };
        Update: {
          display_name?: string | null;
          local_migration_version?: number;
        };
        Relationships: [];
      };
      learning_progress: {
        Row: {
          id: string;
          user_id: string;
          topic_id: string;
          completed: boolean;
          completed_at: string | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          topic_id: string;
          completed: boolean;
          completed_at?: string | null;
        };
        Update: {
          completed?: boolean;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      quiz_attempts: {
        Row: {
          id: string;
          user_id: string;
          quiz_id: string;
          completed_at: string;
          correct_count: number;
          total_questions: number;
          percentage: number;
          answers: unknown;
          created_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          quiz_id: string;
          completed_at: string;
          correct_count: number;
          total_questions: number;
          percentage: number;
          answers: unknown;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      investigation_progress: {
        Row: {
          id: string;
          user_id: string;
          scenario_id: string;
          current_node_id: string;
          history: unknown;
          actions_taken: unknown;
          asked_question_ids: unknown;
          hypothesis_history: unknown;
          business_impact: string | null;
          documentation: unknown;
          completed: boolean;
          score: unknown | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          scenario_id: string;
          current_node_id: string;
          history: unknown;
          actions_taken: unknown;
          asked_question_ids: unknown;
          hypothesis_history: unknown;
          business_impact?: string | null;
          documentation: unknown;
          completed: boolean;
          score?: unknown | null;
        };
        Update: {
          current_node_id?: string;
          history?: unknown;
          actions_taken?: unknown;
          asked_question_ids?: unknown;
          hypothesis_history?: unknown;
          business_impact?: string | null;
          documentation?: unknown;
          completed?: boolean;
          score?: unknown | null;
        };
        Relationships: [];
      };
      investigation_completions: {
        Row: {
          id: string;
          user_id: string;
          scenario_id: string;
          completed_at: string;
          score: number;
          result_category: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          scenario_id: string;
          completed_at: string;
          score: number;
          result_category: string;
        };
        Update: {
          completed_at?: string;
          score?: number;
          result_category?: string;
        };
        Relationships: [];
      };
      daily_logs: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          day_number: number;
          team: string;
          observed: string;
          learned: string;
          new_terminology: string;
          tools_concepts: string;
          questions_asked: string;
          answer_summary: string;
          did_not_understand: string;
          to_research_later: string;
          practice_completed: string;
          tomorrows_goals: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          date: string;
          day_number: number;
          team: string;
          observed?: string;
          learned?: string;
          new_terminology?: string;
          tools_concepts?: string;
          questions_asked?: string;
          answer_summary?: string;
          did_not_understand?: string;
          to_research_later?: string;
          practice_completed?: string;
          tomorrows_goals?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      cv_achievements: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          team: string;
          raw_note: string;
          involvement_level: string;
          skills_involved: string;
          what_learned: string;
          suggested_cv_wording: string;
          evidence_notes: string;
          created_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          date: string;
          team: string;
          raw_note?: string;
          involvement_level: string;
          skills_involved?: string;
          what_learned?: string;
          suggested_cv_wording?: string;
          evidence_notes?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      team_checklist_progress: {
        Row: {
          id: string;
          user_id: string;
          team_id: string;
          item: string;
          completed: boolean;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          team_id: string;
          item: string;
          completed: boolean;
        };
        Update: {
          completed?: boolean;
        };
        Relationships: [];
      };
      tutor_conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          title?: string | null;
        };
        Update: {
          title?: string | null;
        };
        Relationships: [];
      };
      tutor_messages: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: string;
          content: string;
          mode: string;
          related_topic_ids: unknown;
          created_at: string;
        };
        Insert: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: string;
          content: string;
          mode: string;
          related_topic_ids: unknown;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
}
